

CREATE TABLE tbCliente3
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDEREÇO1 VARCHAR(150),
ENDEREÇO2 VARCHAR(150),
BAIRRO VARCHAR (50),
CIDADE VARCHAR (50),
ESTADO VARCHAR (50),
CEP VARCHAR (8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT, 
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMRA BIT(1));

USE SUCOS;
INSERT INTO tbproduto (
PRODUTO,
NOME,
EMBALAGEM,
TAMANHO,
SABOR,
PRECO_LISTA) VALUES (
'1040107', 'Light - 350mil - Melânca', 
'Lata', '350 ml', 'melância', 4.56);

SELECT * FROM tbproduto;






INSERT INTO tabela_de_vendedores (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO) VALUES (
'00235', 'Márcio Almeida Silva',
0.08);

INSERT INTO tabela_de_vendedores (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO) VALUES (
'00236', 'Cláudia Morais',
0.08);

SELECT * FROM tabela_de_vendedores;


UPDATE tabela_de_vendedores SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';

UPDATE tabela_de_vendedores SET NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';

SELECT * FROM tabela_de_vendedores;

DELETE FROM tabela_de_vendedores WHERE MATRICULA = '00233';

SELECT * FROM tabela_de_vendedores;


/*Vamos incluir novos campos na tabela de vendedores. Eles serão a data de admissão
para isso vai ser necessário usar o drop 
*/
USE SUCOS;
DROP TABLE TABELA_DE_VENDEDORES;


USE SUCOS;
CREATE TABLE TABELA_DE_VENDEDORES
( MATRICULA varchar(5),
NOME varchar(100),
PERCENTUAL_COMISSAO float,
DATA_ADMISSAO date,
DE_FERIAS bit);

/*
add
ALTER TABLE TABELA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);
ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_ADMISSÃO DATE);
ALTER TABLE tabela_de_vendedores ADD COLUMN DE_FERIAS BIT(1);
ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);
*/
USE SUCOS;

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00235','Márcio Almeida Silva','2014-08-15',0.08,0);


INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00236','Cláudia Morais','2013-09-17',0.08,1);


INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00237','Roberta Martins','2017-03-18',0.11,1);


INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00238','Pericles Alves','2016-08-21',0.11,0);


SELECT * FROM tabela_de_vendedores;



SELECT NOME, MATRICULA FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_VENDEDORES WHERE NOME = 'Claudia Morais';

SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR(DATA_ADMISSAO) >= 2016;

SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR(DATA_ADMISSAO) < 2016 AND DE_FERIAS = 1;